ServerEvents.recipes(event => {
  event.recipes.gtceu.alloy_smelter('rose_quartz')
    .itemInputs('4x minecraft:redstone', 'minecraft:quartz')
    .itemOutputs('create:rose_quartz')
    .duration(200)
    .EUt(16)
  event.recipes.gtceu.cutter('shaft1')
    .itemInputs('create:andesite_alloy_block')
    .inputFluids('minecraft:water 200')
    .itemOutputs('64x create:shaft')
    .duration(200)
    .EUt(30)
  event.recipes.gtceu.cutter('shaft2')
    .itemInputs('create:andesite_alloy_block')
    .inputFluids('gtceu:distilled_water 100')
    .itemOutputs('64x create:shaft')
    .duration(100)
    .EUt(30)
  event.recipes.gtceu.cutter('shaft3')
    .itemInputs('create:andesite_alloy_block')
    .inputFluids('gtceu:lubricant 50')
    .itemOutputs('64x create:shaft')
    .duration(50)
    .EUt(30)
  event.recipes.gtceu.assembler('andesite_casing')
    .itemInputs('4x gtceu:andesite_alloy_plate', '4x gtceu:treated_wood_plate')
    .itemOutputs('create:andesite_casing')
    .duration(50)
    .EUt(16)
    .circuit(8)
  event.recipes.gtceu.assembler('brass_casing')
    .itemInputs('2x gtceu:brass_plate', '4x gtceu:treated_wood_plate', '2x gtceu:arcane_gold_plate')
    .itemOutputs('create:brass_casing')
    .duration(50)
    .EUt(16)
    .circuit(8)
  event.recipes.gtceu.assembler('copper_casing')
    .itemInputs('4x gtceu:copper_plate', '4x gtceu:treated_wood_plate')
    .itemOutputs('create:copper_casing')
    .duration(50)
    .EUt(16)
    .circuit(8)
  event.recipes.gtceu.assembler('mechanical_pump')
    .itemInputs('2x gtceu:copper_plate', '2x gtceu:andesite_alloy_rotor', 'create:fluid_pipe')
    .itemOutputs('create:mechanical_pump')
    .duration(50)
    .EUt(16)
    .circuit(2)
  event.recipes.gtceu.assembler('controller_rail')
    .itemInputs('12x gtceu:gold_rod', 'minecraft:stick', 'create:electron_tube')
    .itemOutputs('6x create:controller_rail')
    .duration(100)
    .EUt(30)
    .circuit(1)
  event.recipes.gtceu.macerator('cinder_flour')
    .itemInputs('minecraft:red_nether_bricks')
    .itemOutputs('create:cinder_flour')
    .duration(200)
    .EUt(16)
  event.recipes.gtceu.assembler('electron_tube')
    .itemInputs('4x create:polished_rose_quartz', '4x #forge:circuits/ulv')
    .inputFluids('gtceu:glue 200')
    .itemOutputs('4x create:electron_tube')
    .duration(300)
    .EUt(16)
  event.recipes.gtceu.assembler('mechanical_crafter')
    .itemInputs('2x create:electron_tube', 'create:cogwheel', 'create:brass_casing', 'rftoolsbase:crafting_card')
    .itemOutputs('create:mechanical_crafter')
    .duration(200)
    .EUt(16)
  event.recipes.gtceu.assembler('brass_hand')
    .itemInputs('3x eidolon:soul_shard', '3x gtceu:brass_plate', 'gtceu:arcane_gold_plate')
    .itemOutputs('create:brass_hand')
    .duration(200)
    .EUt(16)
  event.recipes.gtceu.assembler('deployer')
    .itemInputs('create:andesite_casing', '2x create:electron_tube', 'create:piston_extension_pole', 'create:brass_hand')
    .itemOutputs('create:deployer')
    .duration(200)
    .EUt(16)
})
