ServerEvents.recipes(event => {
  event.remove({ output: 'botania:apothecary_default' })
  event.shaped('botania:apothecary_default', ['ABA', 'CDC', 'EFE'], { A: 'gtceu:steel_plate', B: '#botania:petals', C: 'gtceu:steel_screw', D: 'minecraft:cauldron', E: '#forge:stone', F: 'gtceu:silver_block' })
  event.remove({ output: 'botania:apothecary_forest' })
  event.shaped('botania:apothecary_forest', ['AAA', 'ABA', 'AAA'], { A: 'botania:metamorphic_forest_cobblestone', B: 'botania:apothecary_default' })
  event.remove({ output: 'botania:apothecary_mossy' })
  event.shaped('botania:apothecary_mossy', ['AAA', 'ABA', 'AAA'], { A: 'minecraft:mossy_cobblestone', B: 'botania:apothecary_default' })
  event.remove({ output: 'botania:apothecary_livingrock' })
  event.shaped('botania:apothecary_livingrock', ['AAA', 'ABA', 'AAA'], { A: 'botania:livingrock', B: 'botania:apothecary_default' })
  event.remove({ output: 'botania:apothecary_deepslate' })
  event.shaped('botania:apothecary_deepslate', ['AAA', 'ABA', 'AAA'], { A: 'minecraft:cobbled_deepslate', B: 'botania:apothecary_default' })
  event.remove({ output: 'botania:apothecary_plains' })
  event.shaped('botania:apothecary_plains', ['AAA', 'ABA', 'AAA'], { A: 'botania:metamorphic_plains_cobblestone', B: 'botania:apothecary_default' })
  event.remove({ output: 'botania:apothecary_mountain' })
  event.shaped('botania:apothecary_mountain', ['AAA', 'ABA', 'AAA'], { A: 'botania:metamorphic_mountain_cobblestone', B: 'botania:apothecary_default' })
  event.remove({ output: 'botania:apothecary_fungal' })
  event.shaped('botania:apothecary_fungal', ['AAA', 'ABA', 'AAA'], { A: 'botania:metamorphic_fungal_cobblestone', B: 'botania:apothecary_default' })
  event.remove({ output: 'botania:apothecary_taiga' })
  event.shaped('botania:apothecary_taiga', ['AAA', 'ABA', 'AAA'], { A: 'botania:metamorphic_taiga_cobblestone', B: 'botania:apothecary_default' })
  event.remove({ output: 'botania:apothecary_swamp' })
  event.shaped('botania:apothecary_swamp', ['AAA', 'ABA', 'AAA'], { A: 'botania:metamorphic_swamp_cobblestone', B: 'botania:apothecary_default' })
  event.remove({ output: 'botania:apothecary_mesa' })
  event.shaped('botania:apothecary_mesa', ['AAA', 'ABA', 'AAA'], { A: 'botania:metamorphic_mesa_cobblestone', B: 'botania:apothecary_default' })
  event.remove({ output: 'botania:apothecary_desert' })
  event.shaped('botania:apothecary_desert', ['AAA', 'ABA', 'AAA'], { A: 'botania:metamorphic_desert_cobblestone', B: 'botania:apothecary_default' })
})
